### ISSUE TITLE
im useing cygwin. is that a problem ?

### ISSUE THREAD

**Issue by adamramadhan** [defunkt/github-gem#27]
$ github issues closed
/usr/lib/ruby/1.8/open-uri.rb:277:in `open_http': 401 Unauthorized (OpenURI::HTTPError)

**Comment by drnic** [comment]
Is this still an issue? Try 0.6.0 and let me know.

**Comment by tombouctou** [comment]
vissi@vissi-K53SJ:~/git/misc$ gh issues open 
/usr/lib/ruby/1.8/open-uri.rb:277:in `open_http': 401 Unauthorized (OpenURI::HTTPError)
    from /usr/lib/ruby/1.8/open-uri.rb:616:in`buffer_open'
    from /usr/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
    from /usr/lib/ruby/1.8/open-uri.rb:162:in`catch'
    from /usr/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
    from /usr/lib/ruby/1.8/open-uri.rb:132:in`open_uri'
    from /usr/lib/ruby/1.8/open-uri.rb:518:in `open'
    from /usr/lib/ruby/1.8/open-uri.rb:30:in`open'
    from /var/lib/gems/1.8/gems/github-0.6.2/lib/commands/issues.rb:10:in `command'
    from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github/command.rb:25:in`send'
    from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github/command.rb:25:in `call'
    from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github.rb:76:in`invoke'
    from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github.rb:70:in `activate'
    from /var/lib/gems/1.8/gems/github-0.6.2/bin/gh:8
    from /var/lib/gems/1.8/bin/gh:19:in`load'
    from /var/lib/gems/1.8/bin/gh:19

ubuntu 11.04

**Comment by cj** [comment]
I get the same error

**Comment by rosewd1954** [comment]
Thanks for accepting me. let me introduce my self to you,Am Mrs Delane Franco, A christian 58 years old,I have a donation to donate,Am a widow from manila phillipine, Recently my Doctor told me that I would not last for the next five months due to cancer problem. i decided to donate this fund to an organization or good person that will utilize this money the way I am going to instruct herein. Meanwhile I am not afraid of death hence I know where I am going. Whoever that Wants to serve the Lord must serve him in truth and faith, "serving him with all you have, knowing that naked we come and naked we must go" Contact me on the this email address (francodelane AT outlook.fr) and any delay in your reply will give me room in sourcing another good person, organization for this same purpose. Please assure me that you will act accordingly as I Stated herein. Remain bless in the lord. Your Sister in christ . Delane Franco
