### ISSUE TITLE
json parse error

### ISSUE THREAD

**Issue by ehaselwanter** [defunkt/github-gem#39]
gh network list
/Library/Ruby/Gems/1.8/gems/json-1.4.6/lib/json/common.rb:146:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
        from /Library/Ruby/Gems/1.8/gems/json-1.4.6/lib/json/common.rb:146:in`new'
        from /Library/Ruby/Gems/1.8/gems/json-1.4.6/lib/json/common.rb:146:in `parse'
        from /Library/Ruby/Gems/1.8/gems/github-0.5.0/lib/commands/helpers.rb:400:in`get_cache'

**Comment by ento** [comment]
In my case, I hadn't told git about my github credentials. From github-gem's readme:

> Authentication
> 
> To let GitHub know who you are, just have your git config set up with your GitHub username and token.

```
$ git config --global github.user "your-github-username"
$ git config --global github.token "your-github-token"
```

> You can find your token under your [account](https://github.com/account/admin).

After setting that up, `gh network list` worked  smoothly.

**Comment by jasonm** [comment]
I still see this issue, even after adding those configs.  Happens in ruby 1.8.7 and 1.9.2 with github gem versino 0.6.2.

**Comment by encukou** [comment]
I also get this error.

**Comment by paulp** [comment]
I had this very frustrating issue for a long time (is spewing a stack trace really the best error message available?) and finally fixed it by removing GITHUB_USER and GITHUB_TOKEN from my gitconfig and hardcoding my actual credentials.

**Comment by jjb** [comment]
I'm having the same problem. None of the proposed solutions work for me.

**Comment by savs** [comment]
Same error.

**Comment by subblue** [comment]
Issue here too with ruby 1.9.2p290, json 1.6.5, json-pure 1.5.4 and github 0.6.2

**Comment by evan** [comment]
The github gem will drop an invalid empty "network cache" file at .git/network-cache if the credentials are busted. Remove it, fix your credentials, then try.

**Comment by shaneog** [comment]
Same error for me, tried with multiple repositories, both personal and part of an organisation.

I tried removing the `.git/network_cache` file also but it still doesn't work

**Comment by akaihola** [comment]
This issue isn't relevant currently because the `network list` command doesn't work at all since GitHub deprecated the v2 API.
