### ISSUE TITLE
github issues does not work with private (user and organization) repos

### ISSUE THREAD

**Issue by ghuntley** [defunkt/github-gem#58]
$ gh issues [open|closed]

```
/usr/lib/ruby/1.8/open-uri.rb:277:in `open_http': 401 Unauthorized (OpenURI::HTTPError)
from /usr/lib/ruby/1.8/open-uri.rb:616:in `buffer_open'
from /usr/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
from /usr/lib/ruby/1.8/open-uri.rb:162:in `catch'
from /usr/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
from /usr/lib/ruby/1.8/open-uri.rb:132:in `open_uri'
from /usr/lib/ruby/1.8/open-uri.rb:518:in `open'
from /usr/lib/ruby/1.8/open-uri.rb:30:in `open'
from /var/lib/gems/1.8/gems/github-0.6.2/lib/commands/issues.rb:10:in `command'
from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github/command.rb:25:in `send'
from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github/command.rb:25:in `call'
from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github.rb:76:in `invoke'
from /var/lib/gems/1.8/gems/github-0.6.2/bin/../lib/github.rb:70:in `activate'
from /var/lib/gems/1.8/gems/github-0.6.2/bin/gh:8
from /var/lib/gems/1.8/bin/gh:19:in `load'
from /var/lib/gems/1.8/bin/gh:19
```

**Comment by ghuntley** [comment]
Fixed in https://github.com/defunkt/github-gem/pull/59

**Comment by nikreiman** [comment]
I'm getting 404's whenever using the issues command on a public organization repo:

> github issues open --verbose
> /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:277:in `open_http': 404 Not Found (OpenURI::HTTPError)
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:616:in`buffer_open'
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:162:in`catch'
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:132:in`open_uri'
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:518:in `open'
>     from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/open-uri.rb:30:in`open'
>     from /Library/Ruby/Gems/1.8/gems/github-0.7.2/lib/commands/issues.rb:10:in `command'
>     from /Library/Ruby/Gems/1.8/gems/github-0.7.2/bin/../lib/github/command.rb:25:in`send'
>     from /Library/Ruby/Gems/1.8/gems/github-0.7.2/bin/../lib/github/command.rb:25:in `call'
>     from /Library/Ruby/Gems/1.8/gems/github-0.7.2/bin/../lib/github.rb:76:in`invoke'
>     from /Library/Ruby/Gems/1.8/gems/github-0.7.2/bin/../lib/github.rb:70:in `activate'
>     from /Library/Ruby/Gems/1.8/gems/github-0.7.2/bin/github:8

Is this a known issue?
