### ISSUE TITLE
Problem on Windows 7 (still claims to require win32-open3 w/ 1.9.2)

### ISSUE THREAD

**Issue by eviljosh** [defunkt/github-gem#75]
I'm running into a problem on Windows 7 x64, where the github gem claims to require win32-open3 even though this functionality (I think?) is baked into ruby 1.9.2.

I tried installing a work-around I found via Google, win32-open3-19, but then got the following error trace when trying to run 'gh create-from-local':

C:/RubyOnRails/Ruby1.9.2/lib/ruby/1.9.1/open3.rb:202:in `spawn': No such file or directory - pwd (Errno::ENOENT)
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/1.9.1/open3.rb:202:in`popen_run'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/1.9.1/open3.rb:90:in `popen3'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github/command.rb:127:in`run'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github/command.rb:61:in `sh'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/commands/commands.rb:242:in`block in load'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github/command.rb:25:in `call'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github.rb:76:in`invoke'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github.rb:70:in `activate'
        from C:/RubyOnRails/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/bin/gh:8:in`<top (required)>'
        from C:/RubyOnRails/Ruby1.9.2/bin/gh:19:in `load'
        from C:/RubyOnRails/Ruby1.9.2/bin/gh:19:in`<main>'

**Comment by polymatter** [comment]
I believe I am getting the same problem, with a fresh install using latest Railsinstaller on Windows 7

C:\Sites\sciteachplan>gh --help
You must 'gem install win32-open3' to use the github command on Windows

C:\Sites\sciteachplan>gem install win32-open3
ERROR:  Error installing win32-open3:
        win32-open3 requires Ruby version < 1.9.0.

On the suggestion above, installing win32-open3-19 initially works to get the help menu up.

C:\Sites\sciteachplan>gem install "win32-open3-19"
Fetching: win32-open3-19-0.0.1.gem (100%)
Successfully installed win32-open3-19-0.0.1
1 gem installed
Installing ri documentation for win32-open3-19-0.0.1...
Installing RDoc documentation for win32-open3-19-0.0.1...

C:\Sites\sciteachplan>gh --help
Usage: github command <space separated arguments>
Available commands:
 ....

But then when building local I get the following:

C:\Sites\sciteachplan>gh create-from-local
Please enter your GitHub credentials:
Username: polymatter
Your account token is at https://github.com/account under 'Account Admin'.
Press Enter to launch page in browser.
Token: <token removed>
C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/open3.rb:202:in 'spawn': No such file or directory - curl -F 'repository[name]=sciteachplan' -F 'repository[public]=true' -F 'login='polymatter'' -F 'token='<token removed>' https://github.com/repositories (Errno::ENOENT)
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/open3.rb:202:in 'popen_run'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/1.9.1/open3.rb:90:in 'popen3'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github/command.rb:127:in 'run'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github/command.rb:61:in 'sh'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/commands/commands.rb:246:in 'block in load'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github/command.rb:25:in 'call'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github.rb:76:in 'invoke'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/lib/github.rb:70:in 'activate'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/github-0.6.2/bin/gh:8:in '&lt;top (required)&gt;'
        from C:/RailsInstaller/Ruby1.9.2/bin/gh:19:in 'load'
        from C:/RailsInstaller/Ruby1.9.2/bin/gh:19:in '&lt;main&gt;'

some of the formatting went a bit weird with the error above, and I thought it would be useful to indicate this occured with vanilla railsinstaller on windows.

**Comment by byousri** [comment]
still open?

**Comment by riverblufftrail** [comment]
I have the same issue. Any ideas?

**Comment by djeremh** [comment]
get the same issue !

**Comment by ddierickx** [comment]
same issue, please fix...

**Comment by ghost** [comment]
Same issue here

**Comment by magee** [comment]
Same problem.

**Comment by MartinOST** [comment]
Same issue here. Help would be greatly appreciated.

**Comment by ghost** [comment]
Same issue

**Comment by ramatgan** [comment]
+1 on this

**Comment by cyberarm** [comment]
Same issue

**Comment by xxxazxxx** [comment]
same issue

**Comment by leemour** [comment]
same issue

**Comment by cbusacca** [comment]
same problem here....

**Comment by ewillyb** [comment]
Same here.

**Comment by domainadmin** [comment]
same here... :(

**Comment by hickford** [comment]
Scott, this sucks!

```
$ ruby --version
ruby 1.9.3p0 (2011-10-30) [i386-mingw32]

$ gem install github
Successfully installed github-0.6.2

$ gh
You must 'gem install win32-open3' to use the github command on Windows

$ gem install win32-open3
Fetching: win32-open3-0.3.2-x86-mingw32.gem (100%)
ERROR:  Error installing win32-open3:
        win32-open3 requires Ruby version < 1.9.0.
```

**Comment by ryenus** [comment]
will this be fixed? I'm still seeing the same error as in previous comment.

**Comment by RyannosaurusRex** [comment]
+1 to ryenus.  Will this be fixed or do I need to look for alternatives?

**Comment by NurjanovUlugbek** [comment]
How fix it? help me

**Comment by anonprotag** [comment]
same issue

**Comment by guillaume86** [comment]
+1 same problem here

**Comment by dev-amit** [comment]
Still the same Problem,
Any fix-up guys !!!
