### ISSUE TITLE
gh issues openssh error

### ISSUE THREAD

**Issue by atomi** [defunkt/github-gem#85]
`gh issues open`

```
D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 st
ate=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/net/http.rb:799:in `connect'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/net/http.rb:744:in `start'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:677:in `open'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/commands/issues.rb:10:i
n `block in load'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/github/command.rb:25:in
 `call'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/github.rb:76:in `invoke
'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/github.rb:70:in `activa
te'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/lib/ruby/gems/1.9.1/gems/github-0.7.2/bin/gh:8:in `<top (required
)>'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/bin/gh:23:in `load'
        from D:/Dropbox/Downloads/Environment/ruby-1.9.3-p194-i386-mingw32/bin/gh:23:in `<main>'
```

**Comment by atomi** [comment]
Follow instructions here:
https://gist.github.com/867550

It says to point user environment variable SSL_CERT_FILE to the file cacert.pem, which you can download at http://curl.haxx.se/ca/cacert.pem

Works now.
