### ISSUE TITLE
create-from-local is broken.

### ISSUE THREAD

**Issue by c9s** [defunkt/github-gem#86]

**Comment by rstacruz** [comment]
To elucidate:

``` sh
$ gh create-from-local
/Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/json_pure-1.5.4/lib/json/common.rb:148:in `encode': "\xC2" on US-ASCII (Encoding::InvalidByteSequenceError)
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/json_pure-1.5.4/lib/json/common.rb:148:in `initialize'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/json_pure-1.5.4/lib/json/common.rb:148:in `new'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/json_pure-1.5.4/lib/json/common.rb:148:in `parse'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/commands/commands.rb:260:in `block in load'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/github/command.rb:25:in `call'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/github.rb:76:in `invoke'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/github-0.7.2/lib/github.rb:70:in `activate'
    from /Users/rsc/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/github-0.7.2/bin/gh:8:in `<top (required)>'
    from /Users/rsc/.rbenv/versions/1.9.3-p194/bin/gh:23:in `load'
    from /Users/rsc/.rbenv/versions/1.9.3-p194/bin/gh:23:in `<main>'
```

``` sh
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin10.8.0]
```

**Comment by DanielKehoe** [comment]
Yep. `github create-from-local` is broken:

```
$ github create-from-local
/Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/json_pure-1.5.4/lib/json/common.rb:148:in `encode': "\xC2" on US-ASCII (Encoding::InvalidByteSequenceError)
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/json_pure-1.5.4/lib/json/common.rb:148:in `initialize'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/json_pure-1.5.4/lib/json/common.rb:148:in `new'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/json_pure-1.5.4/lib/json/common.rb:148:in `parse'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/github-0.7.2/lib/commands/commands.rb:260:in `block in load'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/github-0.7.2/lib/github/command.rb:25:in `call'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/github-0.7.2/lib/github.rb:76:in `invoke'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/github-0.7.2/lib/github.rb:70:in `activate'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/gems/github-0.7.2/bin/github:8:in `<top (required)>'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/bin/github:19:in `load'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/bin/github:19:in `<main>'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/danielkehoe/.rvm/gems/ruby-1.9.3-p194@rails_apps_composer/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by danroux** [comment]
doesn't not work for me either.

**Comment by adamwong246** [comment]
+1
