### ISSUE TITLE
`create` fails on Ruby 2.0.0-preview2

### ISSUE THREAD

**Issue by gavinhughes** [defunkt/github-gem#95]
~ github create

/Users/gavinhughes/.rbenv/versions/2.0.0-preview2/lib/ruby/2.0.0/fileutils.rb:1598:in `path': can't convert nil into String (TypeError)

**Comment by myfairsyer** [comment]
Same here on Win8:

```
λ github create
C:/tools/ruby23/lib/ruby/2.3.0/fileutils.rb:1564:in `path': no implicit conversion of nil into String (TypeError)
        from C:/tools/ruby23/lib/ruby/2.3.0/fileutils.rb:1564:in `block in fu_list'
        from C:/tools/ruby23/lib/ruby/2.3.0/fileutils.rb:1564:in `map'
        from C:/tools/ruby23/lib/ruby/2.3.0/fileutils.rb:1564:in `fu_list'
        from C:/tools/ruby23/lib/ruby/2.3.0/fileutils.rb:177:in `mkdir'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/github-0.7.2/lib/commands/commands.rb:197:in `block in load'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/github-0.7.2/lib/github/command.rb:25:in `call'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/github-0.7.2/lib/github.rb:76:in `invoke'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/github-0.7.2/lib/github.rb:70:in `activate'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/github-0.7.2/bin/github:8:in `<top (required)>'
        from C:/tools/ruby23/bin/github:23:in `load'
        from C:/tools/ruby23/bin/github:23:in `<main>'
```
